export const data = [{
    imgSrc: 'https://th.bing.com/th/id/OIP.wSTCfMrxzjhhb3_b-BPxmAHaFV?w=229&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
    destTitle: 'Bora bora',
    location: 'New Zealand',
    grade: 'Cultura relax',
    fees: '$700',
    description: "It's composed of Hooks, Aos Library (Animation), React-Icons and video background, follow through the tutorial to learn about it's development from scratch.",
}, {
    imgSrc: 'https://th.bing.com/th/id/OIP.wSTCfMrxzjhhb3_b-BPxmAHaFV?w=229&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
    destTitle: 'Bora bora',
    location: 'New Zealand',
    grade: 'Cultura relax',
    fees: '$700',
    description: "It's composed of Hooks, Aos Library (Animation), React-Icons and video background, follow through the tutorial to learn about it's development from scratch.",
}, {
    imgSrc: 'https://th.bing.com/th/id/OIP.wSTCfMrxzjhhb3_b-BPxmAHaFV?w=229&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
    destTitle: 'Bora bora',
    location: 'New Zealand',
    grade: 'Cultura relax',
    fees: '$700',
    description: "It's composed of Hooks, Aos Library (Animation), React-Icons and video background, follow through the tutorial to learn about it's development from scratch.",
}, {
    imgSrc: 'https://th.bing.com/th/id/OIP.wSTCfMrxzjhhb3_b-BPxmAHaFV?w=229&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
    destTitle: 'Bora bora',
    location: 'New Zealand',
    grade: 'Cultura relax',
    fees: '$700',
    description: "It's composed of Hooks, Aos Library (Animation), React-Icons and video background, follow through the tutorial to learn about it's development from scratch.",
}, {
    imgSrc: 'https://th.bing.com/th/id/OIP.wSTCfMrxzjhhb3_b-BPxmAHaFV?w=229&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
    destTitle: 'Bora bora',
    location: 'New Zealand',
    grade: 'Cultura relax',
    fees: '$700',
    description: "It's composed of Hooks, Aos Library (Animation), React-Icons and video background, follow through the tutorial to learn about it's development from scratch.",
}, {
    imgSrc: 'https://th.bing.com/th/id/OIP.wSTCfMrxzjhhb3_b-BPxmAHaFV?w=229&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
    destTitle: 'Bora bora',
    location: 'New Zealand',
    grade: 'Cultura relax',
    fees: '$700',
    description: "It's composed of Hooks, Aos Library (Animation), React-Icons and video background, follow through the tutorial to learn about it's development from scratch.",
}, {
    imgSrc: 'https://th.bing.com/th/id/OIP.wSTCfMrxzjhhb3_b-BPxmAHaFV?w=229&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
    destTitle: 'Bora bora',
    location: 'New Zealand',
    grade: 'Cultura relax',
    fees: '$700',
    description: "It's composed of Hooks, Aos Library (Animation), React-Icons and video background, follow through the tutorial to learn about it's development from scratch.",
}, {
    imgSrc: 'https://th.bing.com/th/id/OIP.wSTCfMrxzjhhb3_b-BPxmAHaFV?w=229&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
    destTitle: 'Bora bora',
    location: 'New Zealand',
    grade: 'Cultura relax',
    fees: '$700',
    description: "It's composed of Hooks, Aos Library (Animation), React-Icons and video background, follow through the tutorial to learn about it's development from scratch.",
}, {
    imgSrc: 'https://th.bing.com/th/id/OIP.wSTCfMrxzjhhb3_b-BPxmAHaFV?w=229&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
    destTitle: 'Bora bora',
    location: 'New Zealand',
    grade: 'Cultura relax',
    fees: '$700',
    description: "It's composed of Hooks, Aos Library (Animation), React-Icons and video background, follow through the tutorial to learn about it's development from scratch.",
}];